### ISSUE TITLE
Bug if output_dir not set

### ISSUE THREAD

**Issue by chrisquince** [xapple/seqenv#1]
If `output_dir` is not specified program throws error:

    Traceback (most recent call last):
      File "/home/chris/repos/seqenv/seqenv/seqenv", line 59, in <module>
        seqenv.Analysis(input_path, **kwargs).run()
      File "/home/chris/repos/seqenv/seqenv/analysis.py", line 128, in __init__
        if not os.path.exists(self.out_dir): os.makedirs(self.out_dir)
      File "/usr/lib64/python2.7/os.py", line 157, in makedirs
        mkdir(name, mode)
    OSError: [Errno 17] File exists: 'AllSites_C05.fa/'

This seems to be because it attempts to create a directory with exactly the same name as the input file.

**Comment by xapple** [comment]
Fixed in version 1.1.1
