### ISSUE TITLE
0 GI hits and 0 of them had one or more Env0 terms associated with test.fasta

### ISSUE THREAD

**Issue by benkraj** [xapple/seqenv#6]
Hi-

I've been trying for a few days now to get seqenv working without success, so I figured it's time to reach out.

I'm attempting to run seqenv using your test.fasta file [(here)](https://github.com/xapple/seqenv/blob/master/examples/minimal/test.fasta). Against the nt database. 

I can use local blastn, i.e.:
``` blastn -db /fdb/blastdb/nt -query test.fasta >> test.out.txt ```

And I get results for each OTU given, but when I run seqenv using the same input/db parameters:
```seqenv test.fasta --search_db /fdb/blastdb/nt```
```seqenv version 1.3.0 (pid 6085)
Start at: 2017-10-30 12:31:20.710219
Got 0 GI hits and 0 of them had one or more EnvO terms associated.
--> STEP 6: Computing EnvO term frequencies.
Traceback (most recent call last):
  File "/home/krajacichbj/.conda/envs/krajpy/bin/seqenv", line 64, in <module>
    seqenv.Analysis(input_path, **kwargs).run()
  File "/home/krajacichbj/.conda/envs/krajpy/lib/python2.7/site-packages/seqenv/analysis.py", line 151, in run
    self.outputs.make_all()
  File "/home/krajacichbj/.conda/envs/krajpy/lib/python2.7/site-packages/seqenv/outputs.py", line 41, in make_all
    self.tsv_seq_to_concepts()
  File "/home/krajacichbj/.conda/envs/krajpy/lib/python2.7/site-packages/seqenv/outputs.py", line 108, in tsv_seq_to_concepts
    content = self.df_seqs_concepts.to_csv(None, sep=self.sep, float_format=self.float_format)
  File "/home/krajacichbj/.conda/envs/krajpy/lib/python2.7/site-packages/seqenv/common/cache.py", line 35, in retrieve_from_cache
    else: result = f(self)
  File "/home/krajacichbj/.conda/envs/krajpy/lib/python2.7/site-packages/seqenv/outputs.py", line 55, in df_seqs_concepts
    df = pandas.DataFrame(self.a.seq_to_counts)
  File "/home/krajacichbj/.conda/envs/krajpy/lib/python2.7/site-packages/seqenv/common/cache.py", line 35, in retrieve_from_cache
    else: result = f(self)
  File "/home/krajacichbj/.conda/envs/krajpy/lib/python2.7/site-packages/seqenv/analysis.py", line 398, in seq_to_counts
    if not results: raise Exception("We found no isolation sources with your input. Sorry.")
Exception: We found no isolation sources with your input. Sorry.
```

I get nothing back. Is this an issue with the seqenv installation/configuration?
blastn is in my path. When I installed seqenv I had to manually add a pygraphviz and orange from conda, but other than that things went smoothly.

I'm pretty new to python and unix is general, so if you need something more to help diagnose, please let me know.

Thanks for any help you can offer.

-Ben

**Comment by xapple** [comment]
Hi. Thanks for the feedback. Seems like you are running `seqenv` several times in a row with the same output directory. When `seqenv` sees files it created previously it attempts to start where it stopped (here straight at step 6). Could you please delete all outputs and run the seqenv example from the start (step 1).

**Comment by xapple** [comment]
The easiest way to achieve this is like this:

     seqenv test.fasta --search_db /fdb/blastdb/nt --out_dir output 
     rm -rf output
     seqenv test.fasta --search_db /fdb/blastdb/nt --out_dir output
     rm -rf output

**Comment by benkraj** [comment]
That did the trick. Thanks for parsing my error, you've saved me a lot of grief!

Thanks for the nice program as well.

Best,
Ben
